name: PR Review Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-review-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @actions/github @actions/core

      - name: Add review comment to PR
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          node -e "
          const github = require('@actions/github');
          const core = require('@actions/core');
          const token = process.env.GITHUB_TOKEN;
          const octokit = github.getOctokit(token);
          const context = github.context;

          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const pull_number = context.payload.pull_request.number;
          const body = 'This is an automated review comment.';
          const path = 'newfile.py';  // Change to the actual file path
          const position = 3;  // Change to the line number where you want to comment

          octokit.rest.pulls.createReview({
            owner,
            repo,
            pull_number,
            event: 'COMMENT',
            body: 'Automated review comment',
            comments: [
              {
                path,
                position,
                body
              }
            ]
          }).then(() => {
            console.log('Review comment added successfully');
          }).catch((error) => {
            console.error('Error adding review comment', error);
            core.setFailed(error.message);
          });
          "
