name: GPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Ollama and Llama3 Artifact
        uses: actions/download-artifact@v2
        with:
          name: ollama-artifact
          path: .

      - name: Verify Ollama Artifact
        run: |
          if [ ! -f ollama.tar.gz ]; then
            echo "Ollama artifact not found!"
            exit 1
          fi
          echo "Ollama artifact found."

      - name: Extract Ollama and Llama3
        run: |
          echo "Extracting Ollama and Llama3 model..."
          set -x
          tar -xzf ollama.tar.gz -C /
          nohup ollama serve &
          sleep 5
          curl -i http://localhost:11434
          set +x
          echo "Ollama and Llama3 model extracted and server started."

      - name: Download Python Packages Artifact
        uses: actions/download-artifact@v2
        with:
          name: pip-packages-artifact
          path: .

      - name: Verify Python Packages Artifact
        run: |
          if [ ! -f pip-packages.tar.gz ]; then
            echo "Python packages artifact not found!"
            exit 1
          fi
          echo "Python packages artifact found."

      - name: Extract Python Packages
        run: |
          echo "Extracting Python packages..."
          set -x
          tar -xzf pip-packages.tar.gz -C ~
          python3 -m pip install --upgrade pip
          pip install litellm openai python-dotenv --no-index --find-links ~/.cache/pip
          set +x
          echo "Python packages extracted and installed."

      - name: Fetch Base Branch
        run: git fetch origin main:main

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: List All Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Create Diffs Directory
        run: mkdir -p diffs

      - name: Get File Diffs
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Generating diffs for: $changed_files"
          for file in $changed_files; do
            dir_name=$(dirname "$file")
            mkdir -p "diffs/$dir_name"
            if git diff origin/main -- "$file" > "diffs/$file.diff"; then
              echo "Diff for $file generated successfully."
            else
              echo "No diff generated for $file. Skipping."
              rm -f "diffs/$file.diff"
            fi
          done

      - name: Run Python Script
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          python3 chatbot.py "$changed_files"
          cat reviews.txt

      - name: Get Latest Commit ID
        id: get_commit
        run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Add Code Suggestions Comments
        run: |
          commit_id=${{ env.commit_id }}
          file_names=()
          diff=""
          review=""

          # Read from the file reviews.txt
          while IFS= read -r line; do
            if [[ $line == "FILE: "* ]]; then
                file_names+=("${line#FILE: }")
            elif [[ $line == "DIFF: "* ]]; then
              diff=""
              while IFS= read -r diff_line; do
                  [[ $diff_line == "ENDDIFF" ]] && break
                  diff+="$diff_line"$'\n'
              done
            elif [[ $line == "REVIEW: "* ]]; then
                review=""
                while IFS= read -r review_line; do
                    [[ $review_line == "ENDREVIEW" ]] && break
                    review+="$review_line"$'\n'
                done

                # Write the file name and review to aux.txt
                echo "${file_names[-1]}" > aux.txt
                echo -e "$diff" >> aux.txt
                echo -e "$review" >> aux.txt

                # Display the content of aux.txt
                cat aux.txt

                # Parse diff
                hunk_header=$(grep -o '@@ [^@]* @@' <<< "$diff")
                if [[ $hunk_header =~ @@\ -([0-9]+),([0-9]+)\ \+([0-9]+),([0-9]+)\ @@ ]]; then
                  original_start_line="${BASH_REMATCH[1]}"
                  original_line_count="${BASH_REMATCH[2]}"
                  new_start_line="${BASH_REMATCH[3]}"
                  new_line_count="${BASH_REMATCH[4]}"
                  echo "Original Start Line: $original_start_line"
                  echo "Original Line Count: $original_line_count"
                  echo "New Start Line: $new_start_line"
                  echo "New Line Count: $new_line_count"
                elif [[ $hunk_header =~ @@\ -([0-9]+),([0-9]+)\ \+([0-9]+)\ @@ ]]; then
                  original_start_line="${BASH_REMATCH[1]}"
                  original_line_count="${BASH_REMATCH[2]}"
                  new_start_line="${BASH_REMATCH[3]}"
                  echo "Original Start Line: $original_start_line"
                  echo "Original Line Count: $original_line_count"
                  echo "New Start Line: $new_start_line"
                else
                  echo "Failed to parse hunk header"
                  exit 1
                fi

                # Get the first character of the hunk content                
                first_char=$(echo "$diff" | grep -o '@@ [^@]* @@' | sed 's/@@ //; s/ @@//' | cut -c 1)
                echo $first_char
                if [[ "$first_char" == "-" ]]; then
                  side="LEFT"
                  start_line=$original_start_line
                  start_side="LEFT"
                elif [[ "$first_char" == "+" ]]; then
                  side="RIGHT"
                  start_line=$new_start_line
                  start_side="RIGHT"
                fi

                echo $side, $start_line, $start_side, "${file_names[-1]}"

                escaped_comments=$(echo "$(cat aux.txt)" | jq -s -R -r @json)
                curl -s -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
                -d "{\"body\":$escaped_comments, \"commit_id\":\"$commit_id\", \"path\":\"${file_names[-1]}\", \"line\":$start_line, \"side\":\"$side\"}"

                > aux.txt
            fi
          done < reviews.txt
