name: GPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh

      - name: Start Ollama Service
        run: |
          nohup ollama serve &

          sleep 5
          curl -i http://localhost:11434

      - name: Pull Llama3 Model
        run: |
          ollama pull llama3

      - name: Cache Python dependencies
        id: cache-python-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        if: steps.cache-python-deps.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          pip install litellm openai python-dotenv

      - name: Fetch Base Branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.py # Adjust the pattern to match the files you care about

      - name: List All Changed Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Create Diffs Directory
        run: mkdir -p diffs

      - name: Get File Diffs
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Generating diffs for: $changed_files"
          for file in $changed_files; do
            dir_name=$(dirname "$file")
            mkdir -p "diffs/$dir_name"
            if git diff origin/${{ github.event.pull_request.base.ref }} -- "$file" > "diffs/$file.diff"; then
              echo "Diff for $file generated successfully."
            else
              echo "No diff generated for $file. Skipping."
              rm -f "diffs/$file.diff"
            fi
          done

      - name: Run Python Script
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          python3 chatbot.py "$changed_files"
          cat reviews.txt

      - name: Get Latest Commit ID
        id: get_commit
        run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Add Code Suggestions Comments
        run: |
          commit_id=${{ env.commit_id }}
          file_names=()
          diff=""
          review=""

          # Read from the file reviews.txt
          while IFS= re
