name: Setup Environment

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh

      - name: Pull Llama3 Model
        run: |
          ollama pull llama3

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install litellm openai python-dotenv

      - name: Save Ollama and Llama3 as Artifact
        run: |
          tar -czf ollama.tar.gz /usr/local/bin/ollama ~/.ollama
        uses: actions/upload-artifact@v2
        with:
          name: ollama-artifact
          path: ollama.tar.gz

      - name: Save Python Packages as Artifact
        run: |
          tar -czf pip-packages.tar.gz ~/.cache/pip
        uses: actions/upload-artifact@v2
        with:
          name: pip-packages-artifact
          path: pip-packages.tar.gz
