name: Setup Environment

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ollama
        run: |
          echo "Installing Ollama..."
          set -x
          curl -fsSL https://ollama.com/install.sh | sudo -E sh
          set +x
          echo "Ollama installation completed."

      - name: Verify Ollama Installation
        run: |
          if command -v ollama &> /dev/null
          then
              echo "Ollama installed successfully."
          else
              echo "Ollama installation failed."
              exit 1
          fi

      - name: Pull Llama3 Model
        run: |
          echo "Pulling Llama3 model..."
          set -x
          ollama pull llama3
          set +x
          echo "Llama3 model pulled successfully."

      - name: Install Python Dependencies
        run: |
          echo "Installing Python dependencies..."
          set -x
          python3 -m pip install --upgrade pip
          pip install litellm openai python-dotenv
          set +x
          echo "Python dependencies installed successfully."

      - name: Verify Python Installation
        run: |
          if python3 -m pip show litellm openai python-dotenv &> /dev/null
          then
              echo "Python dependencies installed successfully."
          else
              echo "Python dependencies installation failed."
              exit 1
          fi

      - name: Save Ollama and Llama3 as Artifact
        run: |
          echo "Saving Ollama and Llama3 model as an artifact..."
          set -x
          tar -czf ollama.tar.gz /usr/local/bin/ollama ~/.ollama
          set +x
          echo "Artifact created: ollama.tar.gz"
        uses: actions/upload-artifact@v2
        with:
          name: ollama-artifact
          path: ollama.tar.gz

      - name: Save Python Packages as Artifact
        run: |
          echo "Saving Python packages as an artifact..."
          set -x
          tar -czf pip-packages.tar.gz ~/.cache/pip
          set +x
          echo "Artifact created: pip-packages.tar.gz"
        uses: actions/upload-artifact@v2
        with:
          name: pip-packages-artifact
          path: pip-packages.tar.gz
