name: Setup Environment

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ollama
        run: |
          echo "Installing Ollama..."
          curl -fsSL https://ollama.com/install.sh | sudo -E sh
          echo "Ollama installation completed."

      - name: Pull Llama3 Model
        run: |
          echo "Pulling Llama3 model..."
          ollama pull llama3
          echo "Llama3 model pulled successfully."

      - name: Install Python Dependencies
        run: |
          echo "Installing Python dependencies..."
          python3 -m pip install --upgrade pip
          pip install litellm openai python-dotenv
          echo "Python dependencies installed successfully."

      - name: Save Ollama and Llama3 as Artifact
        run: |
          echo "Saving Ollama and Llama3 model as an artifact..."
          tar -czf ollama.tar.gz /usr/local/bin/ollama ~/.ollama
          echo "Artifact created: ollama.tar.gz"
        uses: actions/upload-artifact@v2
        with:
          name: ollama-artifact
          path: ollama.tar.gz

      - name: Save Python Packages as Artifact
        run: |
          echo "Saving Python packages as an artifact..."
          tar -czf pip-packages.tar.gz ~/.cache/pip
          echo "Artifact created: pip-packages.tar.gz"
        uses: actions/upload-artifact@v2
        with:
          name: pip-packages-artifact
          path: pip-packages.tar.gz
