name: Setup Environment

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ollama
        run: |
          echo "Installing Ollama..."
          set -x
          curl -fsSL https://ollama.com/install.sh | sudo -E sh
          set +x
          echo "Ollama installation completed."

      - name: Verify Ollama Installation
        run: |
          if command -v ollama &> /dev/null
          then
              echo "Ollama installed successfully."
          else
              echo "Ollama installation failed."
              exit 1
          fi

      - name: Pull Llama3 Model
        run: |
          echo "Pulling Llama3 model..."
          set -x
          ollama pull llama3
          set +x
